## Comparsion Learning Rate 

In [2]:
import tensorflow as tf

In [1]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [5]:
X = tf.placeholder(tf.float32, [None,3])
Y = tf.placeholder(tf.float32, [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [6]:
# model 
h = tf.nn.softmax(tf.matmul(X, W) + b)
# Cross-entropy loss 
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(h), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [13]:
h

<tf.Tensor 'Softmax:0' shape=(?, 3) dtype=float32>

In [14]:
# test model
prediction = tf.argmax(h,axis=1)
is_correct = tf.equal(prediction, tf.argmax(Y,1)) # bool type 
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32)) # cast b

In [15]:
is_correct

<tf.Tensor 'Equal:0' shape=(?,) dtype=bool>

### Launch graph

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data,Y:y_data})
        print('------------ step: {0}----------- \n\
        cost: {1} \n W_val: \n{2}'.format(step, cost_val, w_val))
    #predict
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    #accracy
    print("ACC:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

------------ step: 0----------- 
        cost: 4.882521629333496 
 W_val: 
[[-1.046028    0.92250156 -1.276922  ]
 [ 0.5055968  -0.9059381   0.7762469 ]
 [-0.22483678 -0.5924802  -0.70351076]]
------------ step: 1----------- 
        cost: 2.618457794189453 
 W_val: 
[[-1.0840883   0.95336413 -1.2697242 ]
 [ 0.3774107  -0.74573267  0.7442275 ]
 [-0.3643075  -0.42138088 -0.73513937]]
------------ step: 2----------- 
        cost: 1.850724697113037 
 W_val: 
[[-1.0939038   0.9717781  -1.2783227 ]
 [ 0.3778778  -0.6164443   0.6144721 ]
 [-0.3673268  -0.29587936 -0.85762155]]
------------ step: 3----------- 
        cost: 1.4301916360855103 
 W_val: 
[[-1.1155152   0.9757971  -1.2607303 ]
 [ 0.29081205 -0.5331923   0.61828583]
 [-0.44336957 -0.22364578 -0.85381234]]
------------ step: 4----------- 
        cost: 1.3058748245239258 
 W_val: 
[[-1.1153857   0.96486217 -1.2499249 ]
 [ 0.31813946 -0.51665986  0.574426  ]
 [-0.40827608 -0.2206803  -0.89187133]]
------------ step: 5----------- 


------------ step: 92----------- 
        cost: 0.7431520819664001 
 W_val: 
[[-1.5475652   0.24833034 -0.10121346]
 [ 0.19662613 -0.05792345  0.23720309]
 [-0.15408014 -0.37356845 -0.99317867]]
------------ step: 93----------- 
        cost: 0.7405214309692383 
 W_val: 
[[-1.5521195   0.24386378 -0.09219259]
 [ 0.19713902 -0.05565793  0.23442468]
 [-0.15280055 -0.3738244  -0.9942023 ]]
------------ step: 94----------- 
        cost: 0.737931489944458 
 W_val: 
[[-1.5566635   0.23945503 -0.08323981]
 [ 0.19766061 -0.05343172  0.23167686]
 [-0.15153167 -0.37406373 -0.99523187]]
------------ step: 95----------- 
        cost: 0.7353816032409668 
 W_val: 
[[-1.5611973   0.23510328 -0.07435434]
 [ 0.19819048 -0.0512442   0.22895947]
 [-0.15027283 -0.3742871  -0.9962673 ]]
------------ step: 96----------- 
        cost: 0.7328708171844482 
 W_val: 
[[-1.5657207   0.23080777 -0.0655354 ]
 [ 0.19872792 -0.04909448  0.2262723 ]
 [-0.14902365 -0.37449482 -0.9973088 ]]
------------ step: 97-----

------------ step: 184----------- 
        cost: 0.6019988656044006 
 W_val: 
[[-1.9268193   0.00407253  0.52229816]
 [ 0.24413331  0.05191191  0.07986076]
 [-0.04869711 -0.3658248  -1.1063056 ]]
------------ step: 185----------- 
        cost: 0.6010941863059998 
 W_val: 
[[-1.930563    0.00265141  0.5274629 ]
 [ 0.24449529  0.05250025  0.07891045]
 [-0.04754331 -0.36564845 -1.1076357 ]]
------------ step: 186----------- 
        cost: 0.6001965999603271 
 W_val: 
[[-1.9342999e+00  1.2474173e-03  5.3260386e-01]
 [ 2.4485348e-01  5.3082079e-02  7.7970423e-02]
 [-4.6388686e-02 -3.6547294e-01 -1.1089659e+00]]
------------ step: 187----------- 
        cost: 0.5993062257766724 
 W_val: 
[[-1.9380302e+00 -1.3965543e-04  5.3772122e-01]
 [ 2.4520792e-01  5.3657494e-02  7.7040561e-02]
 [-4.5233220e-02 -3.6529836e-01 -1.1102959e+00]]
------------ step: 188----------- 
        cost: 0.5984229445457458 
 W_val: 
[[-1.9417540e+00 -1.5099975e-03  5.4281533e-01]
 [ 2.4555862e-01  5.4226641e-02  7.6

### Big learning rate : 1.5 
- cost : nan --> 발산해버림 --> 학습률이 너무 크구나 조절해야겠다

In [27]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

In [29]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data,Y:y_data})
        print('------------ step: {0}----------- \n\
        cost: {1} \n W_val: \n{2}'.format(step, cost_val, w_val))
    #predict
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    #accracy
    print("ACC:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

------------ step: 0----------- 
        cost: 4.583715915679932 
 W_val: 
[[ 1.7594221 -0.8756937 -1.3528192]
 [ 1.9344481  2.879124  -3.0396166]
 [ 1.9770402  1.7639625 -2.9869223]]
------------ step: 1----------- 
        cost: 11.938615798950195 
 W_val: 
[[ 1.1251616  -0.80393314 -0.7903192 ]
 [ 0.77280974  2.5407624  -1.5396166 ]
 [ 0.5228361   1.9056666  -1.6744223 ]]
------------ step: 2----------- 
        cost: 11.363588333129883 
 W_val: 
[[ 1.4764853  -1.7177541  -0.22782183]
 [ 3.1618025  -1.3482251  -0.03962183]
 [ 2.9349642  -1.818959   -0.3619249 ]]
------------ step: 3----------- 
        cost: 25.61907196044922 
 W_val: 
[[ 0.35148716 -1.1552541   0.33467627]
 [-0.96319366  1.2767749   1.4603744 ]
 [-1.1900339   0.993541    0.9505732 ]]
------------ step: 4----------- 
        cost: 9.424295425415039 
 W_val: 
[[ 0.7264509  -0.61485285 -0.58068883]
 [ 1.4742336   3.817935   -3.5182128 ]
 [ 1.2474294   3.716337   -4.2096863 ]]
------------ step: 5----------- 
        c

------------ step: 158----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 159----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 160----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 161----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 162----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 163----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 164----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 165----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 166----------- 
        cost: nan 
 W_val: 
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
------------ step: 

### Small learning rate : 1e-10 
- Step1 과 Step 200 비교했을 때, 학습이 일어나지 않고 있음을 알 수 있다 
- learning rate이 너무 작은거 아닌가 하는 생각

In [30]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [31]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, w_val, _ = sess.run([cost, W, optimizer], feed_dict={X:x_data,Y:y_data})
        print('------------ step: {0}----------- \n\
        cost: {1} \n W_val: \n{2}'.format(step, cost_val, w_val))
    #predict
    print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))
    #accracy
    print("ACC:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

------------ step: 0----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 1----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 2----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 3----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 4----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 5----------- 
  

------------ step: 126----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 127----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 128----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 129----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 130----------- 
        cost: 11.95357894897461 
 W_val: 
[[ 1.3331476  -0.0925939  -1.3619019 ]
 [-2.5057154   1.3607706  -0.46905372]
 [ 0.7655657   2.3180592   0.41121897]]
------------ step: 131---