### 학습률을 잘 조절했음에도 불구하고 NaN
- INPUT 데이터들 사이의 균형이 안맞음  
- Normalized input 으로 조정할 필요가 있다 
1. Min-max scaler 로 normalized input (0~1)

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [5]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [6]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
h = tf.matmul(X, W) + b
# mse 
cost = tf.reduce_mean(tf.square(h - Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, h_val, _ = sess.run(
            [cost, h, train], feed_dict={X:x_data, Y: y_data})
        print('STEP : {0} , Cost: {1} \n Prediction: \n {2}'.format(step, cost_val, h_val))

STEP : 0 , Cost: 1406984126464.0 
 Prediction: 
 [[ -836520.2]
 [-1682806.2]
 [-1324046.5]
 [ -928490.9]
 [-1094073.9]
 [-1103271.4]
 [-1011272.9]
 [-1287236.4]]
STEP : 1 , Cost: 1.5458259377564636e+27 
 Prediction: 
 [[2.7733940e+13]
 [5.5831266e+13]
 [4.3920445e+13]
 [3.0787997e+13]
 [3.6285301e+13]
 [3.6590705e+13]
 [3.3536648e+13]
 [4.2698820e+13]]
STEP : 2 , Cost: inf 
 Prediction: 
 [[-9.1927898e+20]
 [-1.8506028e+21]
 [-1.4558025e+21]
 [-1.0205098e+21]
 [-1.2027254e+21]
 [-1.2128484e+21]
 [-1.1116176e+21]
 [-1.4153101e+21]]
STEP : 3 , Cost: inf 
 Prediction: 
 [[3.0470742e+28]
 [6.1340726e+28]
 [4.8254539e+28]
 [3.3826172e+28]
 [3.9865953e+28]
 [4.0201496e+28]
 [3.6846061e+28]
 [4.6912366e+28]]
STEP : 4 , Cost: inf 
 Prediction: 
 [[-1.0099938e+36]
 [-2.0332211e+36]
 [-1.5994618e+36]
 [-1.1212141e+36]
 [-1.3214108e+36]
 [-1.3325329e+36]
 [-1.2213124e+36]
 [-1.5549736e+36]]
STEP : 5 , Cost: inf 
 Prediction: 
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
STEP : 6 , Co

STEP : 177 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 178 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 179 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 180 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 181 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 182 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 183 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 184 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 185 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 186 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 187 , Cost: nan 
 Prediction: 
 [

STEP : 304 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 305 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 306 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 307 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 308 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 309 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 310 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 311 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 312 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 313 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 314 , Cost: nan 
 Prediction: 
 [

STEP : 435 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 436 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 437 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 438 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 439 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 440 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 441 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 442 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 443 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 444 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 445 , Cost: nan 
 Prediction: 
 [

STEP : 560 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 561 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 562 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 563 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 564 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 565 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 566 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 567 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 568 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 569 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 570 , Cost: nan 
 Prediction: 
 [

STEP : 672 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 673 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 674 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 675 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 676 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 677 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 678 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 679 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 680 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 681 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 682 , Cost: nan 
 Prediction: 
 [

STEP : 794 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 795 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 796 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 797 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 798 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 799 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 800 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 801 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 802 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 803 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 804 , Cost: nan 
 Prediction: 
 [

STEP : 923 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 924 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 925 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 926 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 927 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 928 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 929 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 930 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 931 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 932 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 933 , Cost: nan 
 Prediction: 
 [

STEP : 1051 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1052 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1053 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1054 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1055 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1056 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1057 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1058 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1059 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1060 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1061 , Cost: nan 
 Pred

STEP : 1178 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1179 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1180 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1181 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1182 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1183 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1184 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1185 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1186 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1187 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1188 , Cost: nan 
 Pred

STEP : 1308 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1309 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1310 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1311 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1312 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1313 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1314 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1315 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1316 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1317 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1318 , Cost: nan 
 Pred

STEP : 1436 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1437 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1438 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1439 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1440 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1441 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1442 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1443 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1444 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1445 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1446 , Cost: nan 
 Pred

STEP : 1556 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1557 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1558 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1559 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1560 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1561 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1562 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1563 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1564 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1565 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1566 , Cost: nan 
 Pred

STEP : 1657 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1658 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1659 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1660 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1661 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1662 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1663 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1664 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1665 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1666 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1667 , Cost: nan 
 Pred

STEP : 1784 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1785 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1786 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1787 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1788 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1789 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1790 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1791 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1792 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1793 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1794 , Cost: nan 
 Pred

STEP : 1915 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1916 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1917 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1918 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1919 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1920 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1921 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1922 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1923 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1924 , Cost: nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
STEP : 1925 , Cost: nan 
 Pred

### After min-max scaler with scikit-learn

In [11]:
xy

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]])

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
print(scaler.fit(xy))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [21]:
xy2 = scaler.fit_transform(xy)
xy2

array([[1.        , 1.        , 0.        , 1.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881783, 0.83755792],
       [0.54412549, 0.50274824, 0.57608696, 0.60646801, 0.6606331 ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134, 0.43800918],
       [0.51436   , 0.4258239 , 0.30434783, 0.58504805, 0.42624401],
       [0.49556179, 0.4258239 , 0.31521739, 0.48131134, 0.49276137],
       [0.11436064, 0.        , 0.20652174, 0.22007776, 0.18597238],
       [0.        , 0.07747099, 0.5326087 , 0.        , 0.        ]])

In [22]:
x_data = xy2[:, 0:-1]
y_data = xy2[:, [-1]]

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        if step % 100 == 0:
            cost_val, h_val, _ = sess.run(
                [cost, h, train], feed_dict={X:x_data, Y: y_data})
            print('STEP : {0} , Cost: {1} \n Prediction: \n {2}'.format(step, cost_val, h_val))

STEP : 0 , Cost: 0.02561723068356514 
 Prediction: 
 [[0.75420755]
 [0.90304744]
 [0.7436838 ]
 [0.5039703 ]
 [0.67821467]
 [0.51354635]
 [0.41585663]
 [0.11053847]]
STEP : 100 , Cost: 0.025616951286792755 
 Prediction: 
 [[0.75420576]
 [0.90304506]
 [0.7436817 ]
 [0.5039686 ]
 [0.67821276]
 [0.51354444]
 [0.41585493]
 [0.11053662]]
STEP : 200 , Cost: 0.02561667002737522 
 Prediction: 
 [[0.7542041 ]
 [0.9030426 ]
 [0.74367964]
 [0.5039669 ]
 [0.6782109 ]
 [0.51354265]
 [0.41585326]
 [0.11053475]]
STEP : 300 , Cost: 0.025616398081183434 
 Prediction: 
 [[0.75420237]
 [0.9030403 ]
 [0.7436776 ]
 [0.50396526]
 [0.6782091 ]
 [0.51354086]
 [0.41585156]
 [0.11053289]]
STEP : 400 , Cost: 0.0256161168217659 
 Prediction: 
 [[0.75420064]
 [0.9030377 ]
 [0.74367553]
 [0.50396365]
 [0.6782073 ]
 [0.51353896]
 [0.41584986]
 [0.11053103]]
STEP : 500 , Cost: 0.025615841150283813 
 Prediction: 
 [[0.7541989 ]
 [0.9030354 ]
 [0.7436735 ]
 [0.50396204]
 [0.6782054 ]
 [0.51353717]
 [0.41584826]
 [0.110