# Getting Start Pytorch 
- python-based scientific computing package
- a replacement for numpy to use the power of GPUs
- DL research platform that provides maximum flexibility and speed

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.0.0'

## Tensors

In [3]:
# construct a 5x3 matrix, uninitalized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00],
        [8.5899e+09, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.2609e-35, 1.4013e-45],
        [1.4013e-45,        nan, 0.0000e+00]])


In [4]:
# construct a randomly initalized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.1662, 0.9412, 0.5310],
        [0.4194, 0.1370, 0.5942],
        [0.3799, 0.0749, 0.6034],
        [0.6187, 0.7272, 0.7595],
        [0.0308, 0.2502, 0.2517]])


In [7]:
# construct a matrix filed zeros and of dtype long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(type(x))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
<class 'torch.Tensor'>


In [9]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double) # new_* : take in sizes
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype, same size 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0999, 0.7118, 0.4770],
        [0.5069, 0.2889, 0.1140],
        [0.5700, 0.4018, 0.7144],
        [0.4217, 0.0957, 0.5894],
        [0.8810, 0.7108, 0.1190]])


In [12]:
print(x.size())

torch.Size([5, 3])


## Operations 

In [13]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.3328, 1.3266, 1.1903],
        [0.7467, 1.2054, 0.3284],
        [0.9331, 0.9883, 1.0712],
        [1.0002, 0.4776, 1.5697],
        [0.9019, 1.4418, 0.4997]])


In [16]:
y

tensor([[0.2329, 0.6148, 0.7132],
        [0.2397, 0.9165, 0.2144],
        [0.3631, 0.5865, 0.3568],
        [0.5785, 0.3819, 0.9802],
        [0.0209, 0.7310, 0.3807]])

In [14]:
print(torch.add(x, y))

tensor([[0.3328, 1.3266, 1.1903],
        [0.7467, 1.2054, 0.3284],
        [0.9331, 0.9883, 1.0712],
        [1.0002, 0.4776, 1.5697],
        [0.9019, 1.4418, 0.4997]])


In [15]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.3328, 1.3266, 1.1903],
        [0.7467, 1.2054, 0.3284],
        [0.9331, 0.9883, 1.0712],
        [1.0002, 0.4776, 1.5697],
        [0.9019, 1.4418, 0.4997]])


In [17]:
# in-place
print(y)
y.add_(x)
print(y)

tensor([[0.2329, 0.6148, 0.7132],
        [0.2397, 0.9165, 0.2144],
        [0.3631, 0.5865, 0.3568],
        [0.5785, 0.3819, 0.9802],
        [0.0209, 0.7310, 0.3807]])
tensor([[0.3328, 1.3266, 1.1903],
        [0.7467, 1.2054, 0.3284],
        [0.9331, 0.9883, 1.0712],
        [1.0002, 0.4776, 1.5697],
        [0.9019, 1.4418, 0.4997]])


In [18]:
# Numpy-like indexing
print(x[:, 1])

tensor([0.7118, 0.2889, 0.4018, 0.0957, 0.7108])


In [19]:
print(x)

tensor([[0.0999, 0.7118, 0.4770],
        [0.5069, 0.2889, 0.1140],
        [0.5700, 0.4018, 0.7144],
        [0.4217, 0.0957, 0.5894],
        [0.8810, 0.7108, 0.1190]])


## Resizing/Reshape : torch.view 

In [20]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [21]:
# if you have a one element tensor, use .item()
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.1420])
0.14202535152435303


## Numpy Bridge 

### Converting a torch tensor to a numpy array 

In [29]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [30]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [31]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy Array to Torch tensor 

In [32]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
