# Getting Start Pytorch 
- python-based scientific computing package
- a replacement for numpy to use the power of GPUs
- DL research platform that provides maximum flexibility and speed

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.0.0'

## Tensors

In [3]:
# construct a 5x3 matrix, uninitalized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00],
        [8.5899e+09, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.2609e-35, 1.4013e-45],
        [1.4013e-45,        nan, 0.0000e+00]])


In [4]:
# construct a randomly initalized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.1662, 0.9412, 0.5310],
        [0.4194, 0.1370, 0.5942],
        [0.3799, 0.0749, 0.6034],
        [0.6187, 0.7272, 0.7595],
        [0.0308, 0.2502, 0.2517]])


In [7]:
# construct a matrix filed zeros and of dtype long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(type(x))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
<class 'torch.Tensor'>


In [9]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double) # new_* : take in sizes
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype, same size 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.0999, 0.7118, 0.4770],
        [0.5069, 0.2889, 0.1140],
        [0.5700, 0.4018, 0.7144],
        [0.4217, 0.0957, 0.5894],
        [0.8810, 0.7108, 0.1190]])


In [12]:
print(x.size())

torch.Size([5, 3])
