### tf.reshape
- a shape of [-1] flattens into 1-D

In [18]:
import tensorflow as tf
import numpy as np


In [19]:
def showConstantDetail(t):
    sess = tf.InteractiveSession()
    print(t.eval())
    print('shape :', tf.shape(t))
    print('size  :', tf.size(t))
    print('rank  :', tf.rank(t))
    print(t.get_shape())

    sess.close()

In [30]:
t = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
showConstantDetail(t)

[1 2 3 4 5 6 7 8 9]
shape : Tensor("Shape_7:0", shape=(1,), dtype=int32)
size  : Tensor("Size_7:0", shape=(), dtype=int32)
rank  : Tensor("Rank_7:0", shape=(), dtype=int32)
(9,)


In [29]:
t = tf.reshape(t, [3,3])
showConstantDetail(t)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape : Tensor("Shape_6:0", shape=(2,), dtype=int32)
size  : Tensor("Size_6:0", shape=(), dtype=int32)
rank  : Tensor("Rank_6:0", shape=(), dtype=int32)
(3, 3)


In [37]:
t = tf.constant([[[1, 1], [2, 2]],
                 [[3, 3], [4, 4]]])
showConstantDetail(t)
print('reshape!!', '='*50)
t = tf.reshape(t, [2, 4])
showConstantDetail(t)

[[[1 1]
  [2 2]]

 [[3 3]
  [4 4]]]
shape : Tensor("Shape_16:0", shape=(3,), dtype=int32)
size  : Tensor("Size_16:0", shape=(), dtype=int32)
rank  : Tensor("Rank_16:0", shape=(), dtype=int32)
(2, 2, 2)
reshape!! ==================================================
[[1 1 2 2]
 [3 3 4 4]]
shape : Tensor("Shape_17:0", shape=(2,), dtype=int32)
size  : Tensor("Size_17:0", shape=(), dtype=int32)
rank  : Tensor("Rank_17:0", shape=(), dtype=int32)
(2, 4)


In [38]:
t = tf.constant([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
t = tf.reshape(t, [-1])
showConstantDetail(t)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]
shape : Tensor("Shape_18:0", shape=(1,), dtype=int32)
size  : Tensor("Size_18:0", shape=(), dtype=int32)
rank  : Tensor("Rank_18:0", shape=(), dtype=int32)
(18,)


In [43]:
t = tf.reshape(t, [3, -1])
showConstantDetail(t)

[[1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [5 5 5 6 6 6]]
shape : Tensor("Shape_22:0", shape=(2,), dtype=int32)
size  : Tensor("Size_22:0", shape=(), dtype=int32)
rank  : Tensor("Rank_22:0", shape=(), dtype=int32)
(3, 6)


In [42]:
t = tf.reshape(t, [-1, 6])
showConstantDetail(t)

[[1 1 1 2 2 2]
 [3 3 3 4 4 4]
 [5 5 5 6 6 6]]
shape : Tensor("Shape_21:0", shape=(2,), dtype=int32)
size  : Tensor("Size_21:0", shape=(), dtype=int32)
rank  : Tensor("Rank_21:0", shape=(), dtype=int32)
(3, 6)


In [51]:
t = tf.constant([[[1, 1, 1],
                [2, 2, 2]],
               [[3, 3, 3],
                [4, 4, 4]],
               [[5, 5, 5],
                [6, 6, 6]]])
t = tf.reshape(t, [2, -1,3])
showConstantDetail(t)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]
shape : Tensor("Shape_24:0", shape=(3,), dtype=int32)
size  : Tensor("Size_24:0", shape=(), dtype=int32)
rank  : Tensor("Rank_24:0", shape=(), dtype=int32)
(2, 3, 3)


C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
