## Softmax 
- Cost : Cross - Entropy

![image](https://user-images.githubusercontent.com/33097467/43672109-c9a7f9cc-97e1-11e8-9048-c33db9a5c04d.png)
![image](https://user-images.githubusercontent.com/33097467/43672112-043608e0-97e2-11e8-84db-0f41f35f6b76.png)

### Implemetaition  

In [1]:
import tensorflow as tf

In [2]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
# y_data : one-hot encoding 
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [3]:
X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3 # 분류할 class 의 개수 

In [4]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [5]:
# softmax = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), axis)
h = tf.nn.softmax(tf.matmul(X, W) + b)

In [6]:
# cost
cost = tf.reduce_mean(- tf.reduce_sum(Y * tf.log(h), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [8]:
# run session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X:x_data, Y:y_data})
        if step % 200 == 0:
            print("step: {0}, cost: {1}".format(step, sess.run(cost, feed_dict={X:x_data, Y:y_data})))

step: 0, cost: 4.450742244720459
step: 200, cost: 0.5862985253334045
step: 400, cost: 0.46553871035575867
step: 600, cost: 0.36504673957824707
step: 800, cost: 0.27525192499160767
step: 1000, cost: 0.23870864510536194
step: 1200, cost: 0.2156495749950409
step: 1400, cost: 0.19665716588497162
step: 1600, cost: 0.18069911003112793
step: 1800, cost: 0.1670883744955063
step: 2000, cost: 0.15533973276615143


### Testing

In [15]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    testSet = sess.run(h, feed_dict={X: [[1, 11, 7, 9 ]]})
    print(testSet, sess.run(tf.argmax(testSet, axis=1)))

[[1.3188219e-04 9.9986815e-01 5.7127142e-12]] [1]


In [18]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    all = sess.run(h, feed_dict={X:[ [1, 11, 7, 9],
                                    [1, 3, 4, 3],
                                    [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, axis=1)))

[[8.7655199e-01 1.2344795e-01 1.5075892e-14]
 [3.0363876e-01 6.9633305e-01 2.8245640e-05]
 [5.4376438e-02 8.9992869e-01 4.5694891e-02]] [0 1 1]
