## train step 비교
- step :2000
    * cost : 7.9358
    * prediction = [153.82374, 182.72842, 181.03207, 198.9426, 137.40715]
- step : 20000
    * cost : 0.21331373
    * prediction = [151.87027 184.4484  180.75464 195.70776 142.30098]

In [1]:
import tensorflow as tf

In [8]:
#dataset
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

In [9]:
#placeholders for a tensor
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

In [10]:
# weight, bias, hypothesis
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

h = x1*w1 + x2*w2 + x3*w3 + b

In [11]:
#cost function 
cost = tf.reduce_mean(tf.square(h - y))
#optimizer with small learning rate
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [15]:
# launch session
sess = tf.Session()
# initializze global variables
sess.run(tf.global_variables_initializer())
for step in range(20000):
    cost_val, h_val, _ = sess.run([cost, h, train],
                                 feed_dict={x1: x1_data, x2:x2_data, x3:x3_data, y:y_data})
    if step % 1000 == 0:
        print(step, 'cost: ', cost_val, "\nPrediction:\n", h_val)

0 cost:  8379.108 
Prediction:
 [81.20426  80.08805  88.05676  93.29316  59.085957]
1000 cost:  29.795074 
Prediction:
 [159.74078 179.08119 183.2028  197.19785 135.4938 ]
2000 cost:  17.449474 
Prediction:
 [157.88028 180.35477 182.63033 196.80247 137.14934]
3000 cost:  10.266433 
Prediction:
 [156.45952 181.32686 182.19258 196.50421 138.40956]
4000 cost:  6.0861287 
Prediction:
 [155.37424 182.06906 181.8577  196.27995 139.3684 ]
5000 cost:  3.6522613 
Prediction:
 [154.5448  182.6359  181.60126 196.11206 140.09744]
6000 cost:  2.2342036 
Prediction:
 [153.9105  183.069   181.40466 195.9871  140.6513 ]
7000 cost:  1.4071 
Prediction:
 [153.42508 183.40007 181.25374 195.89476 141.0716 ]
8000 cost:  0.9238075 
Prediction:
 [153.05325 183.6533  181.13765 195.82727 141.39006]
9000 cost:  0.6405666 
Prediction:
 [152.76808 183.84717 181.04817 195.77864 141.63095]
10000 cost:  0.47376594 
Prediction:
 [152.54904 183.99577 180.97902 195.74434 141.81273]
11000 cost:  0.37480327 
Prediction:
