### 학습률을 잘 조절했음에도 불구하고 NaN
- INPUT 데이터들 사이의 균형이 안맞음  
- Normalized input 으로 조정할 필요가 있다 
1. Min-max scaler 로 normalized input (0~1)

In [3]:
import tensorflow as tf
import numpy as np

In [26]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [27]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [6]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
h = tf.matmul(X, W) + b
# mse 
cost = tf.reduce_mean(tf.square(h - Y))
# minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [28]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        if step % 500 == 0:
            cost_val, h_val, _ = sess.run(
                [cost, h, train], feed_dict={X:x_data, Y: y_data})
            print('STEP : {0} , Cost: {1} \n Prediction: \n {2}'.format(step, cost_val, h_val))

STEP : 0 , Cost: 206519353344.0 
 Prediction: 
 [[320992.6 ]
 [646620.9 ]
 [508585.94]
 [356392.94]
 [420101.8 ]
 [423642.12]
 [388251.56]
 [494433.28]]
STEP : 500 , Cost: 2.2689875213590667e+26 
 Prediction: 
 [[-1.0625451e+13]
 [-2.1390122e+13]
 [-1.6826837e+13]
 [-1.1795523e+13]
 [-1.3901654e+13]
 [-1.4018661e+13]
 [-1.2848589e+13]
 [-1.6358807e+13]]
STEP : 1000 , Cost: inf 
 Prediction: 
 [[3.5219490e+20]
 [7.0900450e+20]
 [5.5774826e+20]
 [3.9097856e+20]
 [4.6078914e+20]
 [4.6466748e+20]
 [4.2588385e+20]
 [5.4223477e+20]]
STEP : 1500 , Cost: inf 
 Prediction: 
 [[-1.1673976e+28]
 [-2.3500913e+28]
 [-1.8487319e+28]
 [-1.2959512e+28]
 [-1.5273478e+28]
 [-1.5402031e+28]
 [-1.4116495e+28]
 [-1.7973104e+28]]
STEP : 2000 , Cost: inf 
 Prediction: 
 [[3.8694971e+35]
 [7.7896955e+35]
 [6.1278717e+35]
 [4.2956052e+35]
 [5.0626004e+35]
 [5.1052112e+35]
 [4.6791028e+35]
 [5.9574282e+35]]


### After min-max scaler with scikit-learn

In [11]:
xy

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]])

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler = MinMaxScaler()

In [15]:
print(scaler.fit(xy))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [21]:
xy2 = scaler.fit_transform(xy)
xy2

array([[1.        , 1.        , 0.        , 1.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881783, 0.83755792],
       [0.54412549, 0.50274824, 0.57608696, 0.60646801, 0.6606331 ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134, 0.43800918],
       [0.51436   , 0.4258239 , 0.30434783, 0.58504805, 0.42624401],
       [0.49556179, 0.4258239 , 0.31521739, 0.48131134, 0.49276137],
       [0.11436064, 0.        , 0.20652174, 0.22007776, 0.18597238],
       [0.        , 0.07747099, 0.5326087 , 0.        , 0.        ]])

In [22]:
x_data = xy2[:, 0:-1]
y_data = xy2[:, [-1]]

In [24]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        if step % 100 == 0:
            cost_val, h_val, _ = sess.run(
                [cost, h, train], feed_dict={X:x_data, Y: y_data})
            print('STEP : {0} , Cost: {1} \n Prediction: \n {2}'.format(step, cost_val, h_val))

STEP : 0 , Cost: 0.02561723068356514 
 Prediction: 
 [[0.75420755]
 [0.90304744]
 [0.7436838 ]
 [0.5039703 ]
 [0.67821467]
 [0.51354635]
 [0.41585663]
 [0.11053847]]
STEP : 100 , Cost: 0.025616951286792755 
 Prediction: 
 [[0.75420576]
 [0.90304506]
 [0.7436817 ]
 [0.5039686 ]
 [0.67821276]
 [0.51354444]
 [0.41585493]
 [0.11053662]]
STEP : 200 , Cost: 0.02561667002737522 
 Prediction: 
 [[0.7542041 ]
 [0.9030426 ]
 [0.74367964]
 [0.5039669 ]
 [0.6782109 ]
 [0.51354265]
 [0.41585326]
 [0.11053475]]
STEP : 300 , Cost: 0.025616398081183434 
 Prediction: 
 [[0.75420237]
 [0.9030403 ]
 [0.7436776 ]
 [0.50396526]
 [0.6782091 ]
 [0.51354086]
 [0.41585156]
 [0.11053289]]
STEP : 400 , Cost: 0.0256161168217659 
 Prediction: 
 [[0.75420064]
 [0.9030377 ]
 [0.74367553]
 [0.50396365]
 [0.6782073 ]
 [0.51353896]
 [0.41584986]
 [0.11053103]]
STEP : 500 , Cost: 0.025615841150283813 
 Prediction: 
 [[0.7541989 ]
 [0.9030354 ]
 [0.7436735 ]
 [0.50396204]
 [0.6782054 ]
 [0.51353717]
 [0.41584826]
 [0.110