In [1]:
import tensorflow as tf

In [2]:
# matrix 형태의 data 구조

x_data = [[73, 80, 75],[93, 88, 93],[89, 91,90],[96, 98, 100],[73, 66, 70]]
y_data = [[152], [185], [180],[196],[142]]

In [3]:
# placehoder for a tensor 
# shape : input 의 갯수를 모르므로 none 으로 설정하여 다양한 input 받을 수 있게 함
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:
#hypothesis
h = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(h - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [5]:
# initialize global variables and launch 
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [6]:
for step in range(2001):
    cost_val, h_val, _ = sess.run([cost, h, train], feed_dict={X: x_data, Y:y_data})
    if step % 50 == 0:
        print(step, "Cost: ", cost_val, "\n Prediction: \n", h_val)

0 Cost:  94192.7 
 Prediction: 
 [[-116.68539 ]
 [-145.46011 ]
 [-140.55939 ]
 [-154.30623 ]
 [-111.169876]]
50 Cost:  7.8051786 
 Prediction: 
 [[155.56886]
 [181.87155]
 [181.91286]
 [196.86415]
 [138.52205]]
100 Cost:  7.600848 
 Prediction: 
 [[155.51535]
 [181.90822]
 [181.89642]
 [196.8524 ]
 [138.57007]]
150 Cost:  7.402026 
 Prediction: 
 [[155.46255]
 [181.94438]
 [181.8802 ]
 [196.84084]
 [138.61742]]
200 Cost:  7.2085066 
 Prediction: 
 [[155.41048]
 [181.98009]
 [181.86424]
 [196.82942]
 [138.66414]]
250 Cost:  7.0201693 
 Prediction: 
 [[155.3591 ]
 [182.01529]
 [181.84848]
 [196.81815]
 [138.71024]]
300 Cost:  6.836871 
 Prediction: 
 [[155.30841]
 [182.05002]
 [181.83293]
 [196.80704]
 [138.7557 ]]
350 Cost:  6.6584663 
 Prediction: 
 [[155.25839]
 [182.08429]
 [181.8176 ]
 [196.79607]
 [138.80055]]
400 Cost:  6.484832 
 Prediction: 
 [[155.20906]
 [182.11809]
 [181.80246]
 [196.78526]
 [138.84482]]
450 Cost:  6.315852 
 Prediction: 
 [[155.1604 ]
 [182.15144]
 [181.7875

## learning rate 을 0.01 로 조정  
- nan 값이 출력 
- learning rate 을 더 작게 할 필요가 있다

In [15]:
h = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(h - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

for step in range(2001):
    cost_val, h_val, _ = sess.run([cost, h, train], feed_dict={X: x_data, Y:y_data})
    if step % 50 == 0:
        print(step, "Cost: ", cost_val, "\n Prediction: \n", h_val)

0 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
50 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
100 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
150 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
200 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
250 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
300 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
350 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
400 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
450 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
500 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
550 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
650 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]]
700 Cost:  nan 
 Prediction: 
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]